### PR TITLE
Extend transmutation forms

### PR DESCRIPTION
**Pull request by bhauth**
This should make spider/ice/statue/lich form last forever if the corresponding spell failure is yellow or grey.

### CODE REVIEW

**Comment by NormalPerson7** [comment]
The vote for this is very much in favour of high spell power, so that is what I will go with. I will update this sometime if you don't want to.

**Comment by bhauth** [comment]
Yeah, I noticed. Feel free to do that; I don't really want to be the one to pick the spell power values.

**Comment by NormalPerson7** [comment]
Right yea I'll think about that and discuss it. Probably I'll add a new line at the end of transformations' descriptions saying "At above X bars of power this transformation will last forever"

**Comment by bhauth** [comment]
I changed it to require 1 bar of spell power per spell level instead of yellow/grey failure.

**Comment by NormalPerson7** [comment]
May need to adjust a couple of details about this when in active development, but the general idea is great and I should've merged this a month ago!

**Pull request merged**
